### ISSUE TITLE
problem in dcpo_setup and claassen_setup

### ISSUE THREAD

**Issue by Tyhcass** [fsolt/DCPOtools#33]
@fsolt there is something weird.  I found created two all_data_demmood.csv via dcpo_setup and cls_setup didn't include asianb3 data when I checked differences in country_years between two all data.  Since I am not sure whether it is my raw data problem,  I also double-checked claassen_input_raw.csv and there is no asianb3 data. So, somehow asianb3 data is missing.

**Comment by fsolt** [comment]
Yeah, I've replicated this problem.

<img width="787" alt="Screen Shot 2020-06-11 at 10 34 07 AM" src="https://user-images.githubusercontent.com/6536645/84406507-3f7da400-abcf-11ea-85ad-215268c3be28.png">

I'll dig into it.

**Comment by fsolt** [comment]
Ah, that's better.

<img width="794" alt="Screen Shot 2020-06-11 at 11 05 17 AM" src="https://user-images.githubusercontent.com/6536645/84410078-7ce43080-abd3-11ea-835d-f560b4f1dd97.png">

**Comment by fsolt** [comment]
Good catch, Cassandra!
