### ISSUE TITLE
data set request

### ISSUE THREAD

**Issue by Tyhcass** [fsolt/DCPOtools#42]
@fsolt Fred, could you please add these 103 datasets to DCPO? Thanks 

survey_name_in_opensource | survey_name_myend | survey_name_dcpo | link
-- | -- | -- | --
ZA1543 | ZA1543 |   |  
ZA4231 | ZA4231 |   |  
ZA1542 | ZA1542 |   |  
ZA2959 | ZA2959 |   |  
ZA3086 | ZA3086 |   |  
ZA3171 | ZA3171 |   |  
ZA3387 | ZA3387 |   |  
ZA3507 | ZA3507 |   |  
ZA3627 | ZA3627 |   |  
ZA3639 | ZA3639 |   |  
ZA3904 | ZA3904 |   |  
ZA4056 | ZA4056 |   |  
ZA4229 | ZA4229 |   |  
ZA4411 | ZA4411 |   |  
ZA4506 | ZA4506 |   |  
ZA4530 | ZA4530 |   |  
ZA4565 | ZA4565 |   |  
ZA4819 | ZA4819 |   |  
ZA4971 | ZA4971 |   |  
ZA4994 | ZA4994 |   |  
ZA5234 | ZA5234 |   |  
ZA5449 | ZA5449 |   |  
ZA5481 | ZA5481 |   |  
ZA5567 | ZA5567 |   |  
ZA5612 | ZA5612 |   |  
ZA5685 | ZA5685 |   |  
ZA5689 | ZA5689 |   |  
ZA5876 | ZA5876 |   |  
ZA5913 | ZA5913 |   |  
ZA5928 | ZA5928 |   |  
ZA5932 | ZA5932 |   |  
ZA5998 | ZA5998 |   |  
ZA6643 | ZA6643 |   |  
ZA6694 | ZA6694 |   |  
ZA6788 | ZA6788 |   |  
ZA6863 | ZA6863 |   |  
ZA6928 | ZA6928 |   |  
ZA6963 | ZA6963 |   |  
ZA7489 | ZA7489 |   |  
ZA7562 | ZA7562 |   |  
ZA7576 | ZA7576 |   |  
ZA7601 | ZA7601 |   |  
wvs7_ethiopia | wvs7_ethiopia |   |  
wvs7_iran | wvs7_iran |   |  
wvs7_kyrgyzstan | wvs7_kyrgyzstan |   |  
wvs7_myanmar | wvs7_myanmar |   |  
wvs7_nicaragua | wvs7_nicaragua |   |  
wvs7_philippines | wvs7_philippines |   |  
wvs7_tajikistan | wvs7_tajikistan |   |  
wvs7_vietnam | wvs7_vietnam |   |  
wvs7_zimbabwe | wvs7_zimbabwe |   |  
cses5 | cses5 |   |  
ess_combo | ess_combo |   |  
Pew Research Center Fall 2017   Media and Politics in Western Europe | pew2017_fall |   |  
ZA3979 | ZA3979 |   |  
ZA3983 | ZA3983 |   |  
ZA3986 | ZA3986 |   |  
ZA4246 | ZA4246 |   |  
ZA3680 | ZA3680 |   |  
ZA3950 | ZA3950 |   |  
ZA4747 | ZA4747 |   |  
ZA4850 | ZA4850 |   |  
ZA5070 | ZA5070 |   |  
ZA5800 | ZA5800 |   |  
ZA6670 | ZA6670 |   |  
ZA5695 | ZA5695 |   |  
lits_wave1 |   |   | https://www.ebrd.com/what-we-do/economic-research-and-data/data/lits.html
lits_wave2 |   |   |  
lits_wave3 |   |   |  
Caucasus Barometer | cb2008 |   | https://caucasusbarometer.org/en/downloads/
Caucasus Barometer | cb2009 |   |  
Caucasus Barometer | cb2010 |   |  
Caucasus Barometer | cb2011 |   |  
Caucasus Barometer | cb2012 |   |  
Caucasus Barometer | cb2013 |   |  
Caucasus Barometer | cb2015 |   |  
Caucasus Barometer | cb2017 |   |  
Caucasus Barometer | cb2019 |   |  
ZA5177 | isjp_comb |   |  
ukda6510 | nbb_comb |   |  
Values and Political Change in   Postcommunist Europe | vpcpce_czech |   | https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=4129
Values and Political Change in   Postcommunist Europe | vpcpce_czechpublic |   |  
Values and Political Change in   Postcommunist Europe | vpcpce_hungarian |   |  
Values and Political Change in   Postcommunist Europe | vpcpce_hungarianpublic |  
Values and Political Change in   Postcommunist Europe | vpcpce_russian |   |  
Values and Political Change in   Postcommunist Europe | vpcpce_russianpublic |   |  
Values and Political Change in   Postcommunist Europe | vpcpce_slovakianpublic |  
Values and Political Change in   Postcommunist Europe | vpcpce_ukrainian |   |  
Values and Political Change in   Postcommunist Europe | vpcpce_ukrainianpublic |  
ZA0765 | pa_w1 |   |  
ZA1188 | pa_w2 |   |  
ICPSR_34608 | eass_w1 |   |  
ICPSR_36277 | eass_w2 |   |  
Wellcome Global Monitor 2018 | wellcome2018 |   | https://wellcome.org/reports/wellcome-global-monitor/2018
za6288 | eunb_wave1 |   |  
za6289 | eunb_wave2 |   |  
za6290 | eunb_wave3 |   |  
za6291 | eunb_wave4 |   |  
za6292 | eunb_wave5 |   |  
za6293 | eunb_wave6 |   |  
european vote study | ees_comb |   | https://www.tcd.ie/Political_Science/people/michael_marsh/ees_trend_file.php
za5161 | ees2014 |   |  
icpsr34423 | tat2011 |   |

**Comment by fsolt** [comment]
I'm sure I will eventually be able to get around to this, but a pull request would be much faster, tbh . . .

**Comment by Tyhcass** [comment]
Right, right, it will be much faster! Thanks!

**Comment by fsolt** [comment]
Much (all?) of this was in your PR?  And now [here](8845bdf3cf417b8152974990b320f85d68c506f4)?

**Comment by Tyhcass** [comment]
> Much (all?) of this was in your PR? And now [here](8845bdf3cf417b8152974990b320f85d68c506f4)?

All of this has been included!
