### ISSUE TITLE
 Error in DCPOtools

### ISSUE THREAD

**Issue by Tyhcass** [fsolt/DCPOtools#46]
Error in DCPOtools:::claassen_setup(vars = read_csv("C:/Users/skywa/Dropbox/dcpo_dem_mood/data-raw/mood_dem.csv",  : 
  object 'surveys_data' not found

**Comment by fsolt** [comment]
have to use `library(DCPOtools)`; the `DCPOtools::` or `DCPOtools:::` syntaxes don't work
