### ISSUE TITLE
data-raw: add Arab Barometer 5

### ISSUE THREAD

**Issue by fsolt** [fsolt/DCPOtools#7]
https://www.arabbarometer.org/survey-data/data-downloads

**Comment by fsolt** [comment]
Rounds 1-3 are in per https://github.com/fsolt/DCPOtools/commit/d049fe9ba85a83057996ac954851e6e8d5eb534d

**Comment by fsolt** [comment]
Round 4 is in per 6b0081b

**Comment by fsolt** [comment]
It's available now

**Comment by fsolt** [comment]
Since this dataset wasn't available until late last year, @Tyhcass, I doubt it's in the replication materials, but as you can see I've been wanting to add it for a while, so now's a good time

**Comment by Tyhcass** [comment]
Thanks much, @fsolt!  I will set the year range based on the time range of the replication data.
